name: app-test

x-app-test: &app-test
  build:
    context: .
    target: test
  image: app-test
  volumes:
    - ./app:/app/app
    - ./pyproject.toml:/app/pyproject.toml
    - ./tests:/app/tests

services:
  mypy:
    <<: *app-test
    command: mypy app

  ruff:
    <<: *app-test
    command: sh -c "ruff check && ruff format --check"

  ruff_fix:
    <<: *app-test
    command: sh -c "ruff format && ruff check --fix"

  test_db:
    image: postgres:18
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 20s
    env_file:
      - ./vars/test.db.env

  test_db_migrations:
    <<: *app-test
    command: alembic -c /app/app/storage/db/migrations/alembic.ini upgrade head
    env_file:
      - ./vars/test.app.env
    depends_on:
      test_db:
        condition: service_healthy

  pytest:
    <<: *app-test
    command: pytest -p no:warnings
    env_file:
      - ./vars/test.app.env
    depends_on:
      test_db:
        condition: service_healthy
      test_db_migrations:
        condition: service_completed_successfully
