name: app

services:
  app_db:
    image: postgres:18
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 10s
    ports:
      - 5432:5432
    env_file:
      - ./vars/db.env

  app_migrations:
    image: app
    command: alembic -c /app/app/storage/db/migrations/alembic.ini upgrade head
    depends_on:
      app_db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    env_file:
      - ./vars/app.env

  create_app_migration:
    image: app
    profiles: ["migrations"] # this will not run service by default with docker compose up
    command: alembic -c /app/app/storage/db/migrations/alembic.ini revision --autogenerate -m "${MIGRATION_NAME}"
    depends_on:
      app_db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    env_file:
      - ./vars/app.env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    command: uvicorn app.main:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      app_db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    env_file:
      - ./vars/app.env
